namespace DAL.Migrations
{
    using Entity;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<DAL.Entity.EFContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(DAL.Entity.EFContext context)
        {
            IList<Product> products = new List<Product>();
            products.Add(new Product { ProductName = "Абрикосы", Proteins = 1, Fat = 0, Carbohydrates = 10, CaloricValue = 45 });
            products.Add(new Product { ProductName = "Авокадо", Proteins = 2, Fat = 19, Carbohydrates = 7, CaloricValue = 197 });
            products.Add(new Product { ProductName = "Аджика", Proteins = 2, Fat = 3, Carbohydrates = 8, CaloricValue = 59 });
            products.Add(new Product { ProductName = "Айва", Proteins = 1, Fat = 0, Carbohydrates = 9, CaloricValue = 41 });
            products.Add(new Product { ProductName = "Айсберг", Proteins = 1, Fat = 0, Carbohydrates = 2, CaloricValue = 17 });
            products.Add(new Product { ProductName = "Активиа кефирная 1%", Proteins = 3, Fat = 1, Carbohydrates = 4, CaloricValue = 39 });
            products.Add(new Product { ProductName = "Ананас", Proteins = 0, Fat = 0, Carbohydrates = 12, CaloricValue = 50 });
            products.Add(new Product { ProductName = "Ананас консервированный", Proteins = 0, Fat = 0, Carbohydrates = 16, CaloricValue = 65 });
            products.Add(new Product { ProductName = "Ананас цукаты", Proteins = 1, Fat = 2, Carbohydrates = 15, CaloricValue = 78 });
            products.Add(new Product { ProductName = "Апельсин", Proteins = 2, Fat = 0, Carbohydrates = 9, CaloricValue = 43 });
            products.Add(new Product { ProductName = "Апельсиновый сок", Proteins = 0, Fat = 0, Carbohydrates = 11, CaloricValue = 44 });
            products.Add(new Product { ProductName = "Арахис", Proteins = 25, Fat = 46, Carbohydrates = 13, CaloricValue = 561 });
            products.Add(new Product { ProductName = "Арахис в сахаре", Proteins = 18, Fat = 30, Carbohydrates = 51, CaloricValue = 535 });
            products.Add(new Product { ProductName = "Базилик свежий", Proteins = 3, Fat = 1, Carbohydrates = 4, CaloricValue = 27 });
            products.Add(new Product { ProductName = "Баклажаны", Proteins = 1, Fat = 0, Carbohydrates = 6, CaloricValue = 27 });
            products.Add(new Product { ProductName = "Банан", Proteins = 3, Fat = 3, Carbohydrates = 22, CaloricValue = 97 });
            products.Add(new Product { ProductName = "Баранина вареная", Proteins = 24, Fat = 21, Carbohydrates = 0, CaloricValue = 286 });
            products.Add(new Product { ProductName = "Батон", Proteins = 8, Fat = 3, Carbohydrates = 49, CaloricValue = 264 });
            products.Add(new Product { ProductName = "Бедро индейки", Proteins = 16, Fat = 9, Carbohydrates = 1, CaloricValue = 143 });
            products.Add(new Product { ProductName = "Бекон", Proteins = 15, Fat = 45, Carbohydrates = 2, CaloricValue = 469 });
            products.Add(new Product { ProductName = "Блины обычные", Proteins = 6, Fat = 6, Carbohydrates = 25, CaloricValue = 178 });
            products.Add(new Product { ProductName = "Борщ лёгкий", Proteins = 3, Fat = 2, Carbohydrates = 9, CaloricValue = 58 });
            products.Add(new Product { ProductName = "Брокколи", Proteins = 4, Fat = 1, Carbohydrates = 4, CaloricValue = 33 });
            products.Add(new Product { ProductName = "Брусника", Proteins = 1, Fat = 0, Carbohydrates = 9, CaloricValue = 42 });
            products.Add(new Product { ProductName = "Бульон из говядины", Proteins = 6, Fat = 4, Carbohydrates = 0, CaloricValue = 57 });
            products.Add(new Product { ProductName = "Бульон из куриной грудки", Proteins = 7, Fat = 1, Carbohydrates = 0, CaloricValue = 42 });
            products.Add(new Product { ProductName = "Бульон куриный", Proteins = 3, Fat = 2, Carbohydrates = 1, CaloricValue = 33 });
            products.Add(new Product { ProductName = "Вареная говядина", Proteins = 23, Fat = 16, Carbohydrates = 0, CaloricValue = 236 });
            products.Add(new Product { ProductName = "Вареная колбаса", Proteins = 12, Fat = 22, Carbohydrates = 1, CaloricValue = 253 });
            products.Add(new Product { ProductName = "Вареная куриная грудка", Proteins = 27, Fat = 6, Carbohydrates = 1, CaloricValue = 138 });
            products.Add(new Product { ProductName = "Вареная курица", Proteins = 19, Fat = 9, Carbohydrates = 0, CaloricValue = 150 });
            products.Add(new Product { ProductName = "Вареная морковь", Proteins = 1, Fat = 0, Carbohydrates = 6, CaloricValue = 31 });
            products.Add(new Product { ProductName = "Вареная чечевица", Proteins = 8, Fat = 0, Carbohydrates = 20, CaloricValue = 111 });
            products.Add(new Product { ProductName = "Варёная сгущёнка", Proteins = 7, Fat = 9, Carbohydrates = 55, CaloricValue = 326 });
            products.Add(new Product { ProductName = "Вермишель", Proteins = 11, Fat = 1, Carbohydrates = 72, CaloricValue = 347 });
            products.Add(new Product { ProductName = "Ветчина", Proteins = 16, Fat = 19, Carbohydrates = 2, CaloricValue = 246 });
            products.Add(new Product { ProductName = "Вино белое сухое", Proteins = 0, Fat = 0, Carbohydrates = 0, CaloricValue = 67 });
            products.Add(new Product { ProductName = "Виноград", Proteins = 1, Fat = 1, Carbohydrates = 16, CaloricValue = 69 });
            products.Add(new Product { ProductName = "Вино красное сухое", Proteins = 0, Fat = 0, Carbohydrates = 1, CaloricValue = 70 });
            products.Add(new Product { ProductName = "Вишня", Proteins = 1, Fat = 0, Carbohydrates = 11, CaloricValue = 54 });
            products.Add(new Product { ProductName = "Геркулес", Proteins = 12, Fat = 6, Carbohydrates = 56, CaloricValue = 327 });
            products.Add(new Product { ProductName = "Говядина", Proteins = 20, Fat = 13, Carbohydrates = 0, CaloricValue = 192 });
            products.Add(new Product { ProductName = "Говяжья печень", Proteins = 17, Fat = 3, Carbohydrates = 3, CaloricValue = 110 });
            products.Add(new Product { ProductName = "Голень куриная", Proteins = 20, Fat = 9, Carbohydrates = 0, CaloricValue = 168 });
            products.Add(new Product { ProductName = "Голландский сыр", Proteins = 24, Fat = 30, Carbohydrates = 0, CaloricValue = 373 });
            products.Add(new Product { ProductName = "Голубика", Proteins = 1, Fat = 1, Carbohydrates = 9, CaloricValue = 46 });
            products.Add(new Product { ProductName = "Горбуша", Proteins = 21, Fat = 7, Carbohydrates = 0, CaloricValue = 143 });
            products.Add(new Product { ProductName = "Горох", Proteins = 19, Fat = 3, Carbohydrates = 42, CaloricValue = 256 });
            products.Add(new Product { ProductName = "Гороховое пюре", Proteins = 8, Fat = 1, Carbohydrates = 23, CaloricValue = 106 });
            products.Add(new Product { ProductName = "Горошек зеленый", Proteins = 4, Fat = 0, Carbohydrates = 10, CaloricValue = 59 });
            products.Add(new Product { ProductName = "Горчица", Proteins = 8, Fat = 11, Carbohydrates = 13, CaloricValue = 184 });
            products.Add(new Product { ProductName = "Гранат", Proteins = 2, Fat = 1, Carbohydrates = 14, CaloricValue = 67 });
            products.Add(new Product { ProductName = "Грейпфрут", Proteins = 1, Fat = 0, Carbohydrates = 9, CaloricValue = 41 });
            products.Add(new Product { ProductName = "Грецкие орехи", Proteins = 15, Fat = 65, Carbohydrates = 14, CaloricValue = 697 });
            products.Add(new Product { ProductName = "Гречневая каша рассыпчатая", Proteins = 5, Fat = 1, Carbohydrates = 24, CaloricValue = 131 });
            products.Add(new Product { ProductName = "Гречневая крупа", Proteins = 12, Fat = 4, Carbohydrates = 63, CaloricValue = 329 });
            products.Add(new Product { ProductName = "Грибы белые", Proteins = 9, Fat = 2, Carbohydrates = 3, CaloricValue = 28 });
            products.Add(new Product { ProductName = "Грибы белые сушеные", Proteins = 27, Fat = 7, Carbohydrates = 16, CaloricValue = 239 });
            products.Add(new Product { ProductName = "Грибы грузди", Proteins = 2, Fat = 1, Carbohydrates = 1, CaloricValue = 16 });
            products.Add(new Product { ProductName = "Грибы лисички", Proteins = 2, Fat = 1, Carbohydrates = 1, CaloricValue = 20 });
            products.Add(new Product { ProductName = "Грибы маслята", Proteins = 2, Fat = 1, Carbohydrates = 1, CaloricValue = 9 });
            products.Add(new Product { ProductName = "Грибы опята", Proteins = 2, Fat = 1, Carbohydrates = 1, CaloricValue = 17 });
            products.Add(new Product { ProductName = "Грибы подберёзовики свежие", Proteins = 2, Fat = 1, Carbohydrates = 1, CaloricValue = 17 });
            products.Add(new Product { ProductName = "Грибы шампиньоны", Proteins = 4, Fat = 1, Carbohydrates = 0, CaloricValue = 22 });
            products.Add(new Product { ProductName = "Груша", Proteins = 1, Fat = 0, Carbohydrates = 12, CaloricValue = 51 });
            products.Add(new Product { ProductName = "Груша (сухофрукты)", Proteins = 2, Fat = 0, Carbohydrates = 62, CaloricValue = 246 });
            products.Add(new Product { ProductName = "Дайкон", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 21 });
            products.Add(new Product { ProductName = "Джем мандариновый", Proteins = 0, Fat = 0, Carbohydrates = 72, CaloricValue = 276 });
            products.Add(new Product { ProductName = "Дрожжи", Proteins = 29, Fat = 3, Carbohydrates = 23, CaloricValue = 263 });
            products.Add(new Product { ProductName = "Дыня", Proteins = 1, Fat = 0, Carbohydrates = 8, CaloricValue = 35 });
            products.Add(new Product { ProductName = "Ежевика", Proteins = 2, Fat = 0, Carbohydrates = 5, CaloricValue = 31 });
            products.Add(new Product { ProductName = "Жареное яйцо", Proteins = 14, Fat = 14, Carbohydrates = 1, CaloricValue = 183 });
            products.Add(new Product { ProductName = "Зеленая фасоль", Proteins = 3, Fat = 0, Carbohydrates = 4, CaloricValue = 30 });
            products.Add(new Product { ProductName = "Зеленый лук", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 19 });
            products.Add(new Product { ProductName = "Зелень петрушки", Proteins = 4, Fat = 0, Carbohydrates = 8, CaloricValue = 50 });
            products.Add(new Product { ProductName = "Зелёный горошек \"Бондюэль\"", Proteins = 5, Fat = 0, Carbohydrates = 8, CaloricValue = 60 });
            products.Add(new Product { ProductName = "Земляника", Proteins = 1, Fat = 0, Carbohydrates = 9, CaloricValue = 38 });
            products.Add(new Product { ProductName = "Зефир бело-розовый", Proteins = 1, Fat = 0, Carbohydrates = 80, CaloricValue = 304 });
            products.Add(new Product { ProductName = "Изюм", Proteins = 2, Fat = 0, Carbohydrates = 68, CaloricValue = 280 });
            products.Add(new Product { ProductName = "Имбирь свежий", Proteins = 2, Fat = 1, Carbohydrates = 16, CaloricValue = 72 });
            products.Add(new Product { ProductName = "Индейка (грудка)", Proteins = 19, Fat = 2, Carbohydrates = 0, CaloricValue = 94 });
            products.Add(new Product { ProductName = "Индейка (филе)", Proteins = 20, Fat = 12, Carbohydrates = 0, CaloricValue = 188 });
            products.Add(new Product { ProductName = "Инжир (сухофрукты)", Proteins = 3, Fat = 1, Carbohydrates = 57, CaloricValue = 239 });
            products.Add(new Product { ProductName = "Йогурт Активия", Proteins = 4, Fat = 3, Carbohydrates = 11, CaloricValue = 97 });
            products.Add(new Product { ProductName = "Кабачки жареные", Proteins = 1, Fat = 6, Carbohydrates = 7, CaloricValue = 91 });
            products.Add(new Product { ProductName = "Кабачки цукини", Proteins = 2, Fat = 0, Carbohydrates = 3, CaloricValue = 16 });
            products.Add(new Product { ProductName = "Кабачковая икра", Proteins = 1, Fat = 6, Carbohydrates = 7, CaloricValue = 90 });
            products.Add(new Product { ProductName = "Какао", Proteins = 14, Fat = 9, Carbohydrates = 26, CaloricValue = 234 });
            products.Add(new Product { ProductName = "Какао порошок", Proteins = 23, Fat = 15, Carbohydrates = 29, CaloricValue = 326 });
            products.Add(new Product { ProductName = "Кальмар", Proteins = 18, Fat = 2, Carbohydrates = 1, CaloricValue = 97 });
            products.Add(new Product { ProductName = "Кальмар вареный", Proteins = 18, Fat = 3, Carbohydrates = 1, CaloricValue = 103 });
            products.Add(new Product { ProductName = "Каперсы", Proteins = 2, Fat = 1, Carbohydrates = 4, CaloricValue = 21 });
            products.Add(new Product { ProductName = "Капуста белокочаная", Proteins = 2, Fat = 0, Carbohydrates = 5, CaloricValue = 28 });
            products.Add(new Product { ProductName = "Капуста брокколи замороженая", Proteins = 0, Fat = 0, Carbohydrates = 4, CaloricValue = 21 });
            products.Add(new Product { ProductName = "Капуста брюссельская", Proteins = 4, Fat = 0, Carbohydrates = 4, CaloricValue = 47 });
            products.Add(new Product { ProductName = "Капуста жареная", Proteins = 3, Fat = 6, Carbohydrates = 8, CaloricValue = 88 });
            products.Add(new Product { ProductName = "Капуста квашенная", Proteins = 2, Fat = 0, Carbohydrates = 3, CaloricValue = 23 });
            products.Add(new Product { ProductName = "Капуста морская", Proteins = 1, Fat = 5, Carbohydrates = 0, CaloricValue = 58 });
            products.Add(new Product { ProductName = "Капуста цветная", Proteins = 3, Fat = 0, Carbohydrates = 5, CaloricValue = 34 });
            products.Add(new Product { ProductName = "Картофель", Proteins = 2, Fat = 1, Carbohydrates = 20, CaloricValue = 84 });
            products.Add(new Product { ProductName = "Картофель молодой", Proteins = 2, Fat = 0, Carbohydrates = 16, CaloricValue = 61 });
            products.Add(new Product { ProductName = "Картофель отварной", Proteins = 2, Fat = 1, Carbohydrates = 16, CaloricValue = 83 });
            products.Add(new Product { ProductName = "Картофель печеный", Proteins = 3, Fat = 3, Carbohydrates = 22, CaloricValue = 113 });
            products.Add(new Product { ProductName = "Картофель фри", Proteins = 4, Fat = 17, Carbohydrates = 40, CaloricValue = 323 });
            products.Add(new Product { ProductName = "Каша рисовая", Proteins = 2, Fat = 3, Carbohydrates = 26, CaloricValue = 130 });
            products.Add(new Product { ProductName = "Квас хлебный", Proteins = 0, Fat = 0, Carbohydrates = 5, CaloricValue = 24 });
            products.Add(new Product { ProductName = "Кедровые орехи", Proteins = 15, Fat = 63, Carbohydrates = 17, CaloricValue = 652 });
            products.Add(new Product { ProductName = "Кефир 1%", Proteins = 3, Fat = 1, Carbohydrates = 5, CaloricValue = 45 });
            products.Add(new Product { ProductName = "Кефир 2,5%", Proteins = 3, Fat = 3, Carbohydrates = 4, CaloricValue = 52 });
            products.Add(new Product { ProductName = "Кефир 3,2%", Proteins = 3, Fat = 3, Carbohydrates = 4, CaloricValue = 58 });
            products.Add(new Product { ProductName = "Кешью", Proteins = 21, Fat = 48, Carbohydrates = 20, CaloricValue = 607 });
            products.Add(new Product { ProductName = "Киви", Proteins = 1, Fat = 1, Carbohydrates = 10, CaloricValue = 51 });
            products.Add(new Product { ProductName = "Клубника", Proteins = 1, Fat = 0, Carbohydrates = 7, CaloricValue = 32 });
            products.Add(new Product { ProductName = "Клюква", Proteins = 0, Fat = 0, Carbohydrates = 9, CaloricValue = 43 });
            products.Add(new Product { ProductName = "Конфеты Батончики Рот Фронт с орехами", Proteins = 12, Fat = 32, Carbohydrates = 49, CaloricValue = 379 });
            products.Add(new Product { ProductName = "Коричневый сахар", Proteins = 0, Fat = 0, Carbohydrates = 92, CaloricValue = 393 });
            products.Add(new Product { ProductName = "Котлеты полтавские", Proteins = 26, Fat = 32, Carbohydrates = 6, CaloricValue = 415 });
            products.Add(new Product { ProductName = "Кофе молотый Арабика", Proteins = 12, Fat = 14, Carbohydrates = 3, CaloricValue = 193 });
            products.Add(new Product { ProductName = "Кофе эспрессо крепкий", Proteins = 1, Fat = 2, Carbohydrates = 0, CaloricValue = 19 });
            products.Add(new Product { ProductName = "Кофе \"якобз монарх\" (растворимый)", Proteins = 15, Fat = 0, Carbohydrates = 8, CaloricValue = 97 });
            products.Add(new Product { ProductName = "Крабовые палочки", Proteins = 8, Fat = 2, Carbohydrates = 10, CaloricValue = 85 });
            products.Add(new Product { ProductName = "Краковская колбаса", Proteins = 17, Fat = 39, Carbohydrates = 0, CaloricValue = 420 });
            products.Add(new Product { ProductName = "Креветки (отварные)", Proteins = 18, Fat = 2, Carbohydrates = 0, CaloricValue = 90 });
            products.Add(new Product { ProductName = "Крупа гречневая", Proteins = 12, Fat = 3, Carbohydrates = 65, CaloricValue = 326 });
            products.Add(new Product { ProductName = "Крупа кукурузная", Proteins = 8, Fat = 1, Carbohydrates = 75, CaloricValue = 337 });
            products.Add(new Product { ProductName = "Крупа манная", Proteins = 11, Fat = 1, Carbohydrates = 70, CaloricValue = 330 });
            products.Add(new Product { ProductName = "Крупа овсяная", Proteins = 12, Fat = 6, Carbohydrates = 65, CaloricValue = 328 });
            products.Add(new Product { ProductName = "Крупа рис длиннозерный пропаренный", Proteins = 7, Fat = 1, Carbohydrates = 74, CaloricValue = 333 });
            products.Add(new Product { ProductName = "Крупа рисовая", Proteins = 7, Fat = 11, Carbohydrates = 63, CaloricValue = 330 });
            products.Add(new Product { ProductName = "Крыжовник", Proteins = 1, Fat = 0, Carbohydrates = 10, CaloricValue = 41 });
            products.Add(new Product { ProductName = "Кукуруза консервированная", Proteins = 3, Fat = 2, Carbohydrates = 17, CaloricValue = 87 });
            products.Add(new Product { ProductName = "Кукурузные хлопья", Proteins = 6, Fat = 3, Carbohydrates = 73, CaloricValue = 353 });
            products.Add(new Product { ProductName = "Курага", Proteins = 5, Fat = 0, Carbohydrates = 54, CaloricValue = 232 });
            products.Add(new Product { ProductName = "Куриная печень", Proteins = 19, Fat = 7, Carbohydrates = 1, CaloricValue = 140 });
            products.Add(new Product { ProductName = "Куриные грудки", Proteins = 23, Fat = 6, Carbohydrates = 3, CaloricValue = 144 });
            products.Add(new Product { ProductName = "Куриные окорочка", Proteins = 18, Fat = 11, Carbohydrates = 0, CaloricValue = 170 });
            products.Add(new Product { ProductName = "Курица", Proteins = 21, Fat = 11, Carbohydrates = 1, CaloricValue = 186 });
            products.Add(new Product { ProductName = "Лаваш грузинский", Proteins = 8, Fat = 2, Carbohydrates = 53, CaloricValue = 269 });
            products.Add(new Product { ProductName = "Лайм", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 20 });
            products.Add(new Product { ProductName = "Лапша яичная", Proteins = 10, Fat = 2, Carbohydrates = 64, CaloricValue = 330 });
            products.Add(new Product { ProductName = "Лимон", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 27 });
            products.Add(new Product { ProductName = "Лосось", Proteins = 21, Fat = 10, Carbohydrates = 1, CaloricValue = 172 });
            products.Add(new Product { ProductName = "Лук", Proteins = 1, Fat = 0, Carbohydrates = 9, CaloricValue = 40 });
            products.Add(new Product { ProductName = "Майонез", Proteins = 2, Fat = 57, Carbohydrates = 4, CaloricValue = 550 });
            products.Add(new Product { ProductName = "Майонез 15%", Proteins = 0, Fat = 15, Carbohydrates = 5, CaloricValue = 156 });
            products.Add(new Product { ProductName = "Майонез провансаль 67%", Proteins = 3, Fat = 69, Carbohydrates = 25, CaloricValue = 619 });
            products.Add(new Product { ProductName = "Макароны отварные", Proteins = 4, Fat = 1, Carbohydrates = 23, CaloricValue = 119 });
            products.Add(new Product { ProductName = "Малина", Proteins = 4, Fat = 0, Carbohydrates = 9, CaloricValue = 41 });
            products.Add(new Product { ProductName = "Манго", Proteins = 1, Fat = 0, Carbohydrates = 13, CaloricValue = 62 });
            products.Add(new Product { ProductName = "Мандарин", Proteins = 1, Fat = 1, Carbohydrates = 9, CaloricValue = 40 });
            products.Add(new Product { ProductName = "Маргарин молочный", Proteins = 0, Fat = 82, Carbohydrates = 6, CaloricValue = 745 });
            products.Add(new Product { ProductName = "Мармелад", Proteins = 1, Fat = 0, Carbohydrates = 75, CaloricValue = 302 });
            products.Add(new Product { ProductName = "Маслины", Proteins = 1, Fat = 14, Carbohydrates = 10, CaloricValue = 167 });
            products.Add(new Product { ProductName = "Масло оливковое", Proteins = 1, Fat = 91, Carbohydrates = 3, CaloricValue = 851 });
            products.Add(new Product { ProductName = "Масло подсолнечное", Proteins = 0, Fat = 96, Carbohydrates = 0, CaloricValue = 864 });
            products.Add(new Product { ProductName = "Масло сливочное", Proteins = 1, Fat = 74, Carbohydrates = 1, CaloricValue = 674 });
            products.Add(new Product { ProductName = "Мед", Proteins = 1, Fat = 0, Carbohydrates = 80, CaloricValue = 315 });
            products.Add(new Product { ProductName = "Миндаль", Proteins = 18, Fat = 51, Carbohydrates = 16, CaloricValue = 601 });
            products.Add(new Product { ProductName = "Молоко 0,5%", Proteins = 2, Fat = 1, Carbohydrates = 3, CaloricValue = 35 });
            products.Add(new Product { ProductName = "Молоко 1,5%", Proteins = 3, Fat = 2, Carbohydrates = 5, CaloricValue = 44 });
            products.Add(new Product { ProductName = "Молоко 2,5%", Proteins = 3, Fat = 3, Carbohydrates = 7, CaloricValue = 64 });
            products.Add(new Product { ProductName = "Молоко 3,2%", Proteins = 3, Fat = 3, Carbohydrates = 8, CaloricValue = 67 });
            products.Add(new Product { ProductName = "Молоко сгущёное", Proteins = 7, Fat = 9, Carbohydrates = 56, CaloricValue = 317 });
            products.Add(new Product { ProductName = "Морковь свежая", Proteins = 1, Fat = 0, Carbohydrates = 8, CaloricValue = 35 });
            products.Add(new Product { ProductName = "Мороженое Пломбир", Proteins = 4, Fat = 15, Carbohydrates = 24, CaloricValue = 245 });
            products.Add(new Product { ProductName = "Морская капуста", Proteins = 1, Fat = 2, Carbohydrates = 2, CaloricValue = 37 });
            products.Add(new Product { ProductName = "Мюстли с фруктами", Proteins = 8, Fat = 2, Carbohydrates = 68, CaloricValue = 314 });
            products.Add(new Product { ProductName = "Мясо свинина", Proteins = 26, Fat = 29, Carbohydrates = 7, CaloricValue = 293 });
            products.Add(new Product { ProductName = "Мясо свинина постная", Proteins = 18, Fat = 8, Carbohydrates = 0, CaloricValue = 151 });
            products.Add(new Product { ProductName = "Овощная смесь “Весенние овощи”", Proteins = 3, Fat = 0, Carbohydrates = 4, CaloricValue = 30 });
            products.Add(new Product { ProductName = "Овсянка", Proteins = 9, Fat = 5, Carbohydrates = 46, CaloricValue = 240 });
            products.Add(new Product { ProductName = "Овсянные хлопья \"геркулес\"", Proteins = 11, Fat = 6, Carbohydrates = 51, CaloricValue = 305 });
            products.Add(new Product { ProductName = "Огурцы", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 19 });
            products.Add(new Product { ProductName = "Огурцы маринованные", Proteins = 2, Fat = 0, Carbohydrates = 2, CaloricValue = 16 });
            products.Add(new Product { ProductName = "Оливки", Proteins = 1, Fat = 17, Carbohydrates = 5, CaloricValue = 178 });
            products.Add(new Product { ProductName = "Омлет", Proteins = 10, Fat = 14, Carbohydrates = 3, CaloricValue = 175 });
            products.Add(new Product { ProductName = "Орех грецкий", Proteins = 15, Fat = 64, Carbohydrates = 11, CaloricValue = 671 });
            products.Add(new Product { ProductName = "Отруби овсяные", Proteins = 15, Fat = 7, Carbohydrates = 45, CaloricValue = 305 });
            products.Add(new Product { ProductName = "Отруби пшеничные очищенные", Proteins = 13, Fat = 4, Carbohydrates = 23, CaloricValue = 214 });
            products.Add(new Product { ProductName = "Паприка", Proteins = 3, Fat = 2, Carbohydrates = 7, CaloricValue = 112 });
            products.Add(new Product { ProductName = "Патиссон", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 19 });
            products.Add(new Product { ProductName = "Перепелиное яйцо", Proteins = 13, Fat = 13, Carbohydrates = 0, CaloricValue = 167 });
            products.Add(new Product { ProductName = "Перец сладкий", Proteins = 1, Fat = 0, Carbohydrates = 5, CaloricValue = 26 });
            products.Add(new Product { ProductName = "Перловка отварная", Proteins = 2, Fat = 0, Carbohydrates = 27, CaloricValue = 121 });
            products.Add(new Product { ProductName = "Персики", Proteins = 1, Fat = 1, Carbohydrates = 12, CaloricValue = 51 });
            products.Add(new Product { ProductName = "Персики (сухофрукты)", Proteins = 2, Fat = 0, Carbohydrates = 42, CaloricValue = 168 });
            products.Add(new Product { ProductName = "Петрушка свежая", Proteins = 3, Fat = 1, Carbohydrates = 7, CaloricValue = 38 });
            products.Add(new Product { ProductName = "Печенье", Proteins = 8, Fat = 18, Carbohydrates = 66, CaloricValue = 455 });
            products.Add(new Product { ProductName = "Пиво светлое", Proteins = 0, Fat = 0, Carbohydrates = 4, CaloricValue = 50 });
            products.Add(new Product { ProductName = "Плавленный сыр", Proteins = 15, Fat = 20, Carbohydrates = 2, CaloricValue = 280 });
            products.Add(new Product { ProductName = "Помидоры консервированные", Proteins = 1, Fat = 0, Carbohydrates = 5, CaloricValue = 23 });
            products.Add(new Product { ProductName = "Помидоры свежие", Proteins = 4, Fat = 1, Carbohydrates = 3, CaloricValue = 33 });
            products.Add(new Product { ProductName = "Простокваша", Proteins = 3, Fat = 3, Carbohydrates = 4, CaloricValue = 52 });
            products.Add(new Product { ProductName = "Редис", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 20 });
            products.Add(new Product { ProductName = "Рис отварной", Proteins = 7, Fat = 1, Carbohydrates = 75, CaloricValue = 331 });
            products.Add(new Product { ProductName = "Рожки отварные", Proteins = 3, Fat = 0, Carbohydrates = 24, CaloricValue = 115 });
            products.Add(new Product { ProductName = "Руккола", Proteins = 2, Fat = 1, Carbohydrates = 2, CaloricValue = 24 });
            products.Add(new Product { ProductName = "Рыба скумбрия", Proteins = 16, Fat = 13, Carbohydrates = 1, CaloricValue = 187 });
            products.Add(new Product { ProductName = "Рыба треска", Proteins = 17, Fat = 1, Carbohydrates = 0, CaloricValue = 80 });
            products.Add(new Product { ProductName = "Ряженка", Proteins = 3, Fat = 3, Carbohydrates = 4, CaloricValue = 62 });
            products.Add(new Product { ProductName = "Салат лист", Proteins = 1, Fat = 0, Carbohydrates = 2, CaloricValue = 16 });
            products.Add(new Product { ProductName = "Сахар песок", Proteins = 0, Fat = 0, Carbohydrates = 100, CaloricValue = 396 });
            products.Add(new Product { ProductName = "Свежая капуста", Proteins = 2, Fat = 0, Carbohydrates = 5, CaloricValue = 25 });
            products.Add(new Product { ProductName = "Свежий укроп", Proteins = 3, Fat = 1, Carbohydrates = 6, CaloricValue = 38 });
            products.Add(new Product { ProductName = "Свекла", Proteins = 2, Fat = 1, Carbohydrates = 12, CaloricValue = 61 });
            products.Add(new Product { ProductName = "Сельдь жирная", Proteins = 15, Fat = 15, Carbohydrates = 0, CaloricValue = 204 });
            products.Add(new Product { ProductName = "Сладкая кукуруза в початках", Proteins = 4, Fat = 3, Carbohydrates = 21, CaloricValue = 124 });
            products.Add(new Product { ProductName = "Семечки подсолнечные", Proteins = 26, Fat = 50, Carbohydrates = 9, CaloricValue = 583 });
            products.Add(new Product { ProductName = "Слива садовая", Proteins = 1, Fat = 0, Carbohydrates = 10, CaloricValue = 45 });
            products.Add(new Product { ProductName = "Сливки 10%", Proteins = 3, Fat = 10, Carbohydrates = 4, CaloricValue = 118 });
            products.Add(new Product { ProductName = "Сливки 20%", Proteins = 3, Fat = 20, Carbohydrates = 4, CaloricValue = 206 });
            products.Add(new Product { ProductName = "Сливки 33%", Proteins = 2, Fat = 33, Carbohydrates = 4, CaloricValue = 322 });
            products.Add(new Product { ProductName = "Смесь орехов и сухофруктов экзотик", Proteins = 8, Fat = 26, Carbohydrates = 52, CaloricValue = 466 });
            products.Add(new Product { ProductName = "Сметана 10 %", Proteins = 3, Fat = 10, Carbohydrates = 4, CaloricValue = 118 });
            products.Add(new Product { ProductName = "Сметана 15%", Proteins = 3, Fat = 15, Carbohydrates = 4, CaloricValue = 129 });
            products.Add(new Product { ProductName = "Сметана 20%", Proteins = 3, Fat = 19, Carbohydrates = 6, CaloricValue = 204 });
            products.Add(new Product { ProductName = "Сметана 30 %", Proteins = 2, Fat = 30, Carbohydrates = 3, CaloricValue = 291 });
            products.Add(new Product { ProductName = "Смородина красная", Proteins = 1, Fat = 0, Carbohydrates = 8, CaloricValue = 40 });
            products.Add(new Product { ProductName = "Смородина чёрная", Proteins = 1, Fat = 0, Carbohydrates = 9, CaloricValue = 41 });
            products.Add(new Product { ProductName = "Соевый соус", Proteins = 5, Fat = 0, Carbohydrates = 22, CaloricValue = 36 });
            products.Add(new Product { ProductName = "Сок апельсиновый", Proteins = 1, Fat = 0, Carbohydrates = 11, CaloricValue = 47 });
            products.Add(new Product { ProductName = "Сок грейпфрутовый", Proteins = 0, Fat = 0, Carbohydrates = 10, CaloricValue = 44 });
            products.Add(new Product { ProductName = "Сок лайма", Proteins = 1, Fat = 0, Carbohydrates = 6, CaloricValue = 22 });
            products.Add(new Product { ProductName = "Сок лимонный", Proteins = 1, Fat = 0, Carbohydrates = 5, CaloricValue = 29 });
            products.Add(new Product { ProductName = "Сок мандарина", Proteins = 1, Fat = 0, Carbohydrates = 10, CaloricValue = 43 });
            products.Add(new Product { ProductName = "Сок томатный", Proteins = 0, Fat = 0, Carbohydrates = 5, CaloricValue = 21 });
            products.Add(new Product { ProductName = "Сок яблочный", Proteins = 0, Fat = 0, Carbohydrates = 10, CaloricValue = 44 });
            products.Add(new Product { ProductName = "Соя", Proteins = 34, Fat = 12, Carbohydrates = 27, CaloricValue = 359 });
            products.Add(new Product { ProductName = "Спагетти отварные", Proteins = 7, Fat = 1, Carbohydrates = 46, CaloricValue = 223 });
            products.Add(new Product { ProductName = "Сухари панировочные", Proteins = 12, Fat = 2, Carbohydrates = 74, CaloricValue = 362 });
            products.Add(new Product { ProductName = "Сыворотка", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 22 });
            products.Add(new Product { ProductName = "Сыр 45%", Proteins = 26, Fat = 26, Carbohydrates = 0, CaloricValue = 336 });
            products.Add(new Product { ProductName = "Сыр 50% «Сливочный»", Proteins = 23, Fat = 28, Carbohydrates = 0, CaloricValue = 288 });
            products.Add(new Product { ProductName = "Сыр гауда", Proteins = 24, Fat = 27, Carbohydrates = 2, CaloricValue = 350 });
            products.Add(new Product { ProductName = "Сыр «Лёгкий»", Proteins = 23, Fat = 17, Carbohydrates = 0, CaloricValue = 300 });
            products.Add(new Product { ProductName = "Сырок плавленный \"Дружба\"", Proteins = 6, Fat = 19, Carbohydrates = 0, CaloricValue = 178 });
            products.Add(new Product { ProductName = "Сыр твердый", Proteins = 25, Fat = 27, Carbohydrates = 2, CaloricValue = 358 });
            products.Add(new Product { ProductName = "Тархун", Proteins = 0, Fat = 0, Carbohydrates = 10, CaloricValue = 41 });
            products.Add(new Product { ProductName = "Творог 0%", Proteins = 16, Fat = 0, Carbohydrates = 2, CaloricValue = 75 });
            products.Add(new Product { ProductName = "Творог 1%", Proteins = 17, Fat = 1, Carbohydrates = 2, CaloricValue = 82 });
            products.Add(new Product { ProductName = "Творог 10%", Proteins = 15, Fat = 9, Carbohydrates = 2, CaloricValue = 150 });
            products.Add(new Product { ProductName = "Творог 5 %", Proteins = 17, Fat = 5, Carbohydrates = 2, CaloricValue = 122 });
            products.Add(new Product { ProductName = "Творог 9%", Proteins = 16, Fat = 8, Carbohydrates = 3, CaloricValue = 153 });
            products.Add(new Product { ProductName = "Творожная масса с цукатами", Proteins = 7, Fat = 21, Carbohydrates = 33, CaloricValue = 349 });
            products.Add(new Product { ProductName = "Тесто дрожжевое", Proteins = 7, Fat = 4, Carbohydrates = 43, CaloricValue = 238 });
            products.Add(new Product { ProductName = "Тесто слоеное дрожжевое", Proteins = 7, Fat = 19, Carbohydrates = 40, CaloricValue = 356 });
            products.Add(new Product { ProductName = "Тесто слоёное бездрожжевое", Proteins = 6, Fat = 18, Carbohydrates = 38, CaloricValue = 335 });
            products.Add(new Product { ProductName = "Томатная паста помидорка", Proteins = 1, Fat = 0, Carbohydrates = 15, CaloricValue = 77 });
            products.Add(new Product { ProductName = "Томаты черри", Proteins = 1, Fat = 0, Carbohydrates = 3, CaloricValue = 17 });
            products.Add(new Product { ProductName = "Треска филе", Proteins = 17, Fat = 1, Carbohydrates = 0, CaloricValue = 78 });
            products.Add(new Product { ProductName = "Тушенка говядина высший сорт", Proteins = 15, Fat = 17, Carbohydrates = 0, CaloricValue = 213 });
            products.Add(new Product { ProductName = "Тыква", Proteins = 1, Fat = 0, Carbohydrates = 5, CaloricValue = 22 });
            products.Add(new Product { ProductName = "Урюк (сухофрукты)", Proteins = 5, Fat = 0, Carbohydrates = 51, CaloricValue = 213 });
            products.Add(new Product { ProductName = "Фарш говяжий", Proteins = 18, Fat = 16, Carbohydrates = 0, CaloricValue = 214 });
            products.Add(new Product { ProductName = "Фарш куриный", Proteins = 19, Fat = 10, Carbohydrates = 0, CaloricValue = 166 });
            products.Add(new Product { ProductName = "Фасоль", Proteins = 18, Fat = 1, Carbohydrates = 44, CaloricValue = 263 });
            products.Add(new Product { ProductName = "Фасоль стручковая", Proteins = 2, Fat = 0, Carbohydrates = 4, CaloricValue = 29 });
            products.Add(new Product { ProductName = "Финики (сухофрукты)", Proteins = 2, Fat = 0, Carbohydrates = 72, CaloricValue = 380 });
            products.Add(new Product { ProductName = "Фруктоза", Proteins = 0, Fat = 0, Carbohydrates = 100, CaloricValue = 390 });
            products.Add(new Product { ProductName = "Фундук", Proteins = 15, Fat = 62, Carbohydrates = 11, CaloricValue = 665 });
            products.Add(new Product { ProductName = "Хлеб белый", Proteins = 8, Fat = 3, Carbohydrates = 54, CaloricValue = 254 });
            products.Add(new Product { ProductName = "Хлеб \"бородинский\"", Proteins = 7, Fat = 1, Carbohydrates = 42, CaloricValue = 210 });
            products.Add(new Product { ProductName = "Хлеб пшеничный", Proteins = 8, Fat = 3, Carbohydrates = 50, CaloricValue = 263 });
            products.Add(new Product { ProductName = "Хлеб ржаной", Proteins = 7, Fat = 1, Carbohydrates = 36, CaloricValue = 187 });
            products.Add(new Product { ProductName = "Хлебцы пшеничные", Proteins = 12, Fat = 2, Carbohydrates = 60, CaloricValue = 305 });
            products.Add(new Product { ProductName = "Хлопья кукурузные", Proteins = 7, Fat = 1, Carbohydrates = 84, CaloricValue = 373 });
            products.Add(new Product { ProductName = "Хлопья овсяные", Proteins = 12, Fat = 6, Carbohydrates = 52, CaloricValue = 308 });
            products.Add(new Product { ProductName = "Хрен", Proteins = 3, Fat = 5, Carbohydrates = 14, CaloricValue = 113 });
            products.Add(new Product { ProductName = "Хурма", Proteins = 1, Fat = 0, Carbohydrates = 15, CaloricValue = 65 });
            products.Add(new Product { ProductName = "Цветная капуста отварная", Proteins = 2, Fat = 0, Carbohydrates = 4, CaloricValue = 29 });
            products.Add(new Product { ProductName = "Цедра апельсина", Proteins = 1, Fat = 0, Carbohydrates = 6, CaloricValue = 36 });
            products.Add(new Product { ProductName = "Цедра лимона", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 28 });
            products.Add(new Product { ProductName = "Цукаты", Proteins = 3, Fat = 0, Carbohydrates = 56, CaloricValue = 224 });
            products.Add(new Product { ProductName = "Цукини", Proteins = 2, Fat = 0, Carbohydrates = 3, CaloricValue = 18 });
            products.Add(new Product { ProductName = "Черемша", Proteins = 2, Fat = 0, Carbohydrates = 7, CaloricValue = 37 });
            products.Add(new Product { ProductName = "Черешня", Proteins = 1, Fat = 0, Carbohydrates = 12, CaloricValue = 51 });
            products.Add(new Product { ProductName = "Черника", Proteins = 1, Fat = 0, Carbohydrates = 9, CaloricValue = 39 });
            products.Add(new Product { ProductName = "Чернослив (сухофрукты)", Proteins = 3, Fat = 0, Carbohydrates = 62, CaloricValue = 256 });
            products.Add(new Product { ProductName = "Чеснок", Proteins = 6, Fat = 0, Carbohydrates = 23, CaloricValue = 115 });
            products.Add(new Product { ProductName = "Чечевица зелёная", Proteins = 24, Fat = 2, Carbohydrates = 44, CaloricValue = 286 });
            products.Add(new Product { ProductName = "Чечевица красная", Proteins = 22, Fat = 1, Carbohydrates = 49, CaloricValue = 312 });
            products.Add(new Product { ProductName = "Шампиньоны", Proteins = 4, Fat = 1, Carbohydrates = 1, CaloricValue = 26 });
            products.Add(new Product { ProductName = "Шампиньоны резанные консервированные", Proteins = 2, Fat = 1, Carbohydrates = 1, CaloricValue = 16 });
            products.Add(new Product { ProductName = "Шиповник сушёный", Proteins = 4, Fat = 0, Carbohydrates = 60, CaloricValue = 253 });
            products.Add(new Product { ProductName = "Шоколад горький 75%", Proteins = 9, Fat = 41, Carbohydrates = 39, CaloricValue = 550 });
            products.Add(new Product { ProductName = "Шоколад горький 80%", Proteins = 12, Fat = 39, Carbohydrates = 34, CaloricValue = 527 });
            products.Add(new Product { ProductName = "Шоколад молочный", Proteins = 7, Fat = 34, Carbohydrates = 52, CaloricValue = 539 });
            products.Add(new Product { ProductName = "Шпинат", Proteins = 3, Fat = 0, Carbohydrates = 2, CaloricValue = 22 });
            products.Add(new Product { ProductName = "Щавель", Proteins = 2, Fat = 0, Carbohydrates = 5, CaloricValue = 25 });
            products.Add(new Product { ProductName = "Яблоки", Proteins = 1, Fat = 1, Carbohydrates = 13, CaloricValue = 60 });
            products.Add(new Product { ProductName = "Яблоки сушёные (сухофрукты)", Proteins = 3, Fat = 0, Carbohydrates = 66, CaloricValue = 269 });
            products.Add(new Product { ProductName = "Яйца", Proteins = 15, Fat = 13, Carbohydrates = 1, CaloricValue = 162 });

            context.Products.AddRange(products);
            context.SaveChanges();
        }
    }
}
